version: "3.7"

services:
  app:
    image: learning-docker/node:v4
    volumes:
      - ./:/app
    environment: # phần này ta định nghĩa ở file .env nhé
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

volumes:
  mongodata: